# Generated by Django 4.2.2 on 2023-07-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_album_num_stars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
    ]
